# Generated by Django 2.2 on 2019-05-11 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This will be the name that the Hub, Satelite, Link etc will be known as', max_length=200)),
                ('vault', models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200)),
                ('schema', models.CharField(blank=True, help_text='Can be supplied directly, otherwise, derived from the Vault field', max_length=200)),
                ('table_name', models.CharField(blank=True, help_text='Can be entered explicitly, but if blank will be derived from name, and table_naming rules', max_length=200)),
                ('table_alias', models.CharField(blank=True, help_text='table Alias will be used when this table is used in joins, and select statements', max_length=200)),
                ('root_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Hub')),
            ],
        ),
        migrations.CreateModel(
            name='HubSatelite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This will be the name that the Hub, Satelite, Link etc will be known as', max_length=200)),
                ('vault', models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200)),
                ('schema', models.CharField(blank=True, help_text='Can be supplied directly, otherwise, derived from the Vault field', max_length=200)),
                ('table_name', models.CharField(blank=True, help_text='Can be entered explicitly, but if blank will be derived from name, and table_naming rules', max_length=200)),
                ('table_alias', models.CharField(blank=True, help_text='table Alias will be used when this table is used in joins, and select statements', max_length=200)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('rate_of_change', models.CharField(blank=True, max_length=200)),
                ('create_diff_key', models.BooleanField(blank=True, default=True, help_text='If Yes, this satelite will contain a difference field to look for situations where\n                       this satelite should be replaced with a more recent record ', null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Hub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubSateliteLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.HubLoader')),
                ('hub_satelite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dventities.HubSatelite')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This will be the name that the Hub, Satelite, Link etc will be known as', max_length=200)),
                ('vault', models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200)),
                ('schema', models.CharField(blank=True, help_text='Can be supplied directly, otherwise, derived from the Vault field', max_length=200)),
                ('table_name', models.CharField(blank=True, help_text='Can be entered explicitly, but if blank will be derived from name, and table_naming rules', max_length=200)),
                ('table_alias', models.CharField(blank=True, help_text='table Alias will be used when this table is used in joins, and select statements', max_length=200)),
                ('root_name', models.CharField(blank=True, max_length=200)),
                ('create_diff_key', models.BooleanField(blank=True, default=False, help_text='If True, this link will contain a difference field to look for situations where\n                       this link should be end dated, or reversed                             \n                                                                 ', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LinkSatelite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This will be the name that the Hub, Satelite, Link etc will be known as', max_length=200)),
                ('vault', models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200)),
                ('schema', models.CharField(blank=True, help_text='Can be supplied directly, otherwise, derived from the Vault field', max_length=200)),
                ('table_name', models.CharField(blank=True, help_text='Can be entered explicitly, but if blank will be derived from name, and table_naming rules', max_length=200)),
                ('table_alias', models.CharField(blank=True, help_text='table Alias will be used when this table is used in joins, and select statements', max_length=200)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('rate_of_change', models.CharField(blank=True, max_length=200)),
                ('create_diff_key', models.BooleanField(blank=True, default=True, help_text='If Yes, this satelite will contain a difference field to look for situations where\n                       this satelite should be replaced with a more recent record ', null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkSateliteLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.LinkLoader')),
            ],
        ),
        migrations.CreateModel(
            name='StageTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This will be the name that the Hub, Satelite, Link etc will be known as', max_length=200)),
                ('vault', models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200)),
                ('schema', models.CharField(blank=True, help_text='Can be supplied directly, otherwise, derived from the Vault field', max_length=200)),
                ('table_name', models.CharField(blank=True, help_text='Can be entered explicitly, but if blank will be derived from name, and table_naming rules', max_length=200)),
                ('table_alias', models.CharField(blank=True, help_text='table Alias will be used when this table is used in joins, and select statements', max_length=200)),
                ('root_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageTableField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200)),
                ('field_precision', models.IntegerField(blank=True, null=True)),
                ('field_scale', models.IntegerField(blank=True, null=True)),
                ('field_description', models.CharField(blank=True, max_length=200, null=True)),
                ('field_length', models.IntegerField(blank=True, null=True)),
                ('column_name', models.CharField(blank=True, max_length=200)),
                ('usage', models.CharField(blank=True, choices=[('physical', 'physical'), ('derived', 'derived'), ('augmented', 'augmented')], default='physical', max_length=200)),
                ('stage_table_primary_key', models.BooleanField(blank=True, default=False, help_text='This field represents the primary key of the stage table.  A similar primary key will\n                       be created on the augmented table, and then a view will combined fields in the stage table \n                       with fields in the augmented table', null=True)),
                ('stage_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkSateliteLoaderField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_satelite_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.LinkSateliteLoader')),
                ('stage_table_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTableField')),
            ],
        ),
        migrations.AddField(
            model_name='linksateliteloader',
            name='stage_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTable'),
        ),
        migrations.CreateModel(
            name='LinkSateliteField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200)),
                ('field_precision', models.IntegerField(blank=True, null=True)),
                ('field_scale', models.IntegerField(blank=True, null=True)),
                ('field_description', models.CharField(blank=True, max_length=200, null=True)),
                ('field_length', models.IntegerField(blank=True, null=True)),
                ('column_name', models.CharField(blank=True, max_length=200)),
                ('sat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.LinkSatelite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkLoaderToHubLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forms_part_of_link_diff_key', models.BooleanField(blank=True, default=True, help_text='This hub will be included in the diff key hash ', null=True)),
                ('forms_part_of_link_driving_key', models.BooleanField(blank=True, default=True, help_text='This hub will be included in the driving key of the link ', null=True)),
                ('hub_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.HubLoader')),
                ('link_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.LinkLoader')),
            ],
        ),
        migrations.CreateModel(
            name='LinkLoaderField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forms_part_of_link_diff_key', models.BooleanField(blank=True, default=True, help_text='This field will be included in the diff key hash ', null=True)),
                ('link_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.LinkLoader')),
                ('stage_table_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTableField')),
            ],
        ),
        migrations.AddField(
            model_name='linkloader',
            name='hub_loaders',
            field=models.ManyToManyField(through='dventities.LinkLoaderToHubLoader', to='dventities.HubLoader'),
        ),
        migrations.AddField(
            model_name='linkloader',
            name='stage_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTable'),
        ),
        migrations.CreateModel(
            name='LinkHubReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_alias', models.CharField(blank=True, max_length=200)),
                ('forms_part_of_driving_key', models.BooleanField(blank=True, default=False, help_text='This hub forms part of the driving key, and will trigger\n                       a new link if  a record comes through with the same driving \n                       key but with a differet dif key.  the existing record will be\n                       either end-dated or reversed                                                           \n                                                                 ', null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Hub')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Link')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LinkField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200)),
                ('field_precision', models.IntegerField(blank=True, null=True)),
                ('field_scale', models.IntegerField(blank=True, null=True)),
                ('field_description', models.CharField(blank=True, max_length=200, null=True)),
                ('field_length', models.IntegerField(blank=True, null=True)),
                ('column_name', models.CharField(blank=True, max_length=200)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubSateliteLoaderField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('create_field_like_this_in_satelite', models.BooleanField(blank=True, default=False, help_text='If a field with this name does not exist in the satelite, then\n                       a field will be created when this record is saved ', null=True)),
                ('satelite_field_name', models.CharField(blank=True, help_text='The satelite field that will get populated by load routines ', max_length=200)),
                ('hub_satelite_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.HubSateliteLoader')),
                ('stage_table_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTableField')),
            ],
        ),
        migrations.AddField(
            model_name='hubsateliteloader',
            name='stage_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTable'),
        ),
        migrations.CreateModel(
            name='HubSateliteField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200)),
                ('field_precision', models.IntegerField(blank=True, null=True)),
                ('field_scale', models.IntegerField(blank=True, null=True)),
                ('field_description', models.CharField(blank=True, max_length=200, null=True)),
                ('field_length', models.IntegerField(blank=True, null=True)),
                ('column_name', models.CharField(blank=True, max_length=200)),
                ('sat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dventities.HubSatelite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubLoaderField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('purpose', models.CharField(blank=True, choices=[('hub key field', 'Hub Key Field')], default='hub key field', max_length=200)),
                ('hub_field_name', models.CharField(blank=True, help_text='If left blank, the loader will\n                       look for a hub field whose name is the same as this field.  \n                       If this field is populated, then the loader will load \n                       data into the field specified here ', max_length=200)),
                ('hub_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.HubLoader')),
                ('stage_table_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTableField')),
            ],
        ),
        migrations.AddField(
            model_name='hubloader',
            name='stage_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTable'),
        ),
        migrations.CreateModel(
            name='HubKeyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200)),
                ('field_precision', models.IntegerField(blank=True, null=True)),
                ('field_scale', models.IntegerField(blank=True, null=True)),
                ('field_description', models.CharField(blank=True, max_length=200, null=True)),
                ('field_length', models.IntegerField(blank=True, null=True)),
                ('column_name', models.CharField(blank=True, max_length=200)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Hub')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
