# Generated by Django 2.2.1 on 2019-05-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vault', models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', max_length=200)),
                ('schema', models.CharField(blank=True, max_length=200)),
                ('table_name', models.CharField(blank=True, max_length=200)),
                ('table_alias', models.CharField(blank=True, max_length=200)),
                ('root_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vault', models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', max_length=200)),
                ('schema', models.CharField(blank=True, max_length=200)),
                ('table_name', models.CharField(blank=True, max_length=200)),
                ('table_alias', models.CharField(blank=True, max_length=200)),
                ('root_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkSatelite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vault', models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', max_length=200)),
                ('schema', models.CharField(blank=True, max_length=200)),
                ('table_name', models.CharField(blank=True, max_length=200)),
                ('table_alias', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('rate_of_change', models.CharField(blank=True, max_length=200)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkHubReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_alias', models.CharField(blank=True, max_length=200)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Hub')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Link')),
            ],
        ),
        migrations.CreateModel(
            name='HubSatelite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vault', models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', max_length=200)),
                ('schema', models.CharField(blank=True, max_length=200)),
                ('table_name', models.CharField(blank=True, max_length=200)),
                ('table_alias', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('rate_of_change', models.CharField(blank=True, max_length=200)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Hub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubKeyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(blank=True, max_length=200)),
                ('field_precision', models.IntegerField(blank=True)),
                ('field_scale', models.IntegerField(blank=True)),
                ('field_desciption', models.CharField(blank=True, max_length=200)),
                ('column_name', models.CharField(blank=True, max_length=200)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Hub')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
