# Generated by Django 2.2 on 2019-05-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkloader',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
