# Generated by Django 2.2.1 on 2019-05-05 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0002_auto_20190505_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubHashField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(blank=True, max_length=200)),
                ('field_precision', models.IntegerField(blank=True)),
                ('field_scale', models.IntegerField(blank=True)),
                ('field_desciption', models.CharField(blank=True, max_length=200)),
                ('column_name', models.CharField(blank=True, max_length=200)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Hub')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
