# Generated by Django 2.2 on 2019-05-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0002_linkloader_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkloaderfield',
            name='create_field_like_this_in_link',
            field=models.BooleanField(blank=True, default=False, help_text='If a field with this name does not exist in the link, then\n                       a field will be created when this record is saved ', null=True),
        ),
        migrations.AddField(
            model_name='linkloaderfield',
            name='link_field_name',
            field=models.CharField(blank=True, help_text='The link field that will get populated by load routines ', max_length=200),
        ),
    ]
