# Generated by Django 2.2 on 2019-05-12 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0003_auto_20190512_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkloader',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dventities.Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkloadertohubloader',
            name='hub_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dventities.LinkHubReference'),
        ),
    ]
