# Generated by Django 2.2.1 on 2019-05-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0003_hubhashfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubhashfield',
            name='id',
        ),
        migrations.AlterField(
            model_name='hubhashfield',
            name='hub',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dventities.Hub'),
        ),
    ]
