# Generated by Django 2.2 on 2019-05-13 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0004_auto_20190512_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksateliteloader',
            name='link_satelite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dventities.LinkSatelite'),
            preserve_default=False,
        ),
    ]
