# Generated by Django 2.2 on 2019-05-14 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0005_linksateliteloader_link_satelite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubsatelitefield',
            name='sat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.HubSatelite'),
        ),
    ]
