# Generated by Django 2.2.1 on 2019-05-06 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0005_linkdifferencefield_linkfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Hub')),
            ],
        ),
        migrations.CreateModel(
            name='HubSateliteLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LinkLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LinkSateliteLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StageTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vault', models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', max_length=200)),
                ('schema', models.CharField(blank=True, max_length=200)),
                ('table_name', models.CharField(blank=True, max_length=200)),
                ('table_alias', models.CharField(blank=True, max_length=200)),
                ('root_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageTableField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(blank=True, max_length=200)),
                ('field_precision', models.IntegerField(blank=True)),
                ('field_scale', models.IntegerField(blank=True)),
                ('field_desciption', models.CharField(blank=True, max_length=200)),
                ('column_name', models.CharField(blank=True, max_length=200)),
                ('usage', models.CharField(blank=True, choices=[('physical', 'physical'), ('derived', 'derived'), ('augmented', 'augmented')], default='physical', max_length=200)),
                ('stage_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foo_bar', to='dventities.StageTable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkSateliteLoaderField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_satelite_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.LinkSateliteLoader')),
                ('stage_table_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTableField')),
            ],
        ),
        migrations.AddField(
            model_name='linksateliteloader',
            name='stage_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTable'),
        ),
        migrations.CreateModel(
            name='LinkLoaderField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.LinkLoader')),
                ('stage_table_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTableField')),
            ],
        ),
        migrations.AddField(
            model_name='linkloader',
            name='stage_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTable'),
        ),
        migrations.CreateModel(
            name='HubSateliteLoaderField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_satelite_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.HubSateliteLoader')),
                ('stage_table_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTableField')),
            ],
        ),
        migrations.AddField(
            model_name='hubsateliteloader',
            name='stage_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTable'),
        ),
        migrations.CreateModel(
            name='HubLoaderField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('purpose', models.CharField(blank=True, choices=[('hub key field', 'Hub Key Field')], default='hub key field', max_length=200)),
                ('hub_loader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.HubLoader')),
                ('stage_table_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTableField')),
            ],
        ),
        migrations.AddField(
            model_name='hubloader',
            name='stage_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTable'),
        ),
    ]
