# Generated by Django 2.2 on 2019-05-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0006_auto_20190506_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubkeyfield',
            name='field_length',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkdifferencefield',
            name='field_length',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkfield',
            name='field_length',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagetablefield',
            name='field_length',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hubkeyfield',
            name='field_type',
            field=models.CharField(blank=True, choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200),
        ),
        migrations.AlterField(
            model_name='linkdifferencefield',
            name='field_type',
            field=models.CharField(blank=True, choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200),
        ),
        migrations.AlterField(
            model_name='linkfield',
            name='field_type',
            field=models.CharField(blank=True, choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200),
        ),
        migrations.AlterField(
            model_name='stagetablefield',
            name='field_type',
            field=models.CharField(blank=True, choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200),
        ),
        migrations.DeleteModel(
            name='HubHashField',
        ),
    ]
