# Generated by Django 2.2 on 2019-05-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0007_auto_20190508_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubkeyfield',
            name='field_type',
            field=models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200),
        ),
        migrations.AlterField(
            model_name='hubkeyfield',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_fields', to='dventities.Hub'),
        ),
        migrations.AlterField(
            model_name='linkdifferencefield',
            name='field_type',
            field=models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200),
        ),
        migrations.AlterField(
            model_name='linkfield',
            name='field_type',
            field=models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200),
        ),
        migrations.AlterField(
            model_name='stagetablefield',
            name='field_type',
            field=models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200),
        ),
    ]
