# Generated by Django 2.2 on 2019-05-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0007_linksateliteloaderfield_link_satelite_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksateliteloader',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='linksateliteloader',
            name='create_field_like_this_in_satelite',
            field=models.BooleanField(blank=True, default=False, help_text='If a field with this name does not exist in the satelite, then\n                       a field will be created when this record is saved ', null=True),
        ),
    ]
