# Generated by Django 2.2 on 2019-05-08 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0008_auto_20190508_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSateliteField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200)),
                ('field_precision', models.IntegerField(blank=True)),
                ('field_scale', models.IntegerField(blank=True)),
                ('field_desciption', models.CharField(blank=True, max_length=200)),
                ('field_length', models.IntegerField(blank=True)),
                ('column_name', models.CharField(blank=True, max_length=200)),
                ('sat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dventities.HubSatelite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
