# Generated by Django 2.2 on 2019-05-09 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0009_hubsatelitefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkSateliteField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('datetime', 'datetime')], max_length=200)),
                ('field_precision', models.IntegerField(blank=True)),
                ('field_scale', models.IntegerField(blank=True)),
                ('field_desciption', models.CharField(blank=True, max_length=200)),
                ('field_length', models.IntegerField(blank=True)),
                ('column_name', models.CharField(blank=True, max_length=200)),
                ('sat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.LinkSatelite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='linkhubreference',
            name='forms_part_of_driving_key',
            field=models.BooleanField(blank=True, default=False, help_text='This hub forms part of the driving key, and will trigger\n                       a new link if  a record comes through with the same driving \n                       key but with a differet dif key.  the existing record will be\n                       either end-dated or reversed                                                           \n                                                                 ', null=True),
        ),
        migrations.DeleteModel(
            name='LinkDifferenceField',
        ),
    ]
