# Generated by Django 2.2 on 2019-05-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0010_auto_20190509_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='create_diff_key',
            field=models.BooleanField(blank=True, default=False, help_text='If True, this link will contain a difference field to look for situations where\n                       this link should be end dated, or reversed                             \n                                                                 ', null=True),
        ),
    ]
