# Generated by Django 2.2 on 2019-05-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0011_link_create_diff_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubsatelite',
            name='create_diff_key',
            field=models.BooleanField(blank=True, default=True, help_text='If Yes, this satelite will contain a difference field to look for situations where\n                       this satelite should be replaced with a more recent record ', null=True),
        ),
        migrations.AddField(
            model_name='linksatelite',
            name='create_diff_key',
            field=models.BooleanField(blank=True, default=True, help_text='If Yes, this satelite will contain a difference field to look for situations where\n                       this satelite should be replaced with a more recent record ', null=True),
        ),
    ]
