# Generated by Django 2.2 on 2019-05-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0012_auto_20190509_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='name',
            field=models.CharField(help_text='This will be the name that the Hub, Satelite, Link etc will be known as', max_length=200),
        ),
        migrations.AlterField(
            model_name='hub',
            name='schema',
            field=models.CharField(blank=True, help_text='Can be supplied directly, otherwise, derived from the Vault field', max_length=200),
        ),
        migrations.AlterField(
            model_name='hub',
            name='table_alias',
            field=models.CharField(blank=True, help_text='table Alias will be used when this table is used in joins, and select statements', max_length=200),
        ),
        migrations.AlterField(
            model_name='hub',
            name='table_name',
            field=models.CharField(blank=True, help_text='Can be entered explicitly, but if blank will be derived from name, and table_naming rules', max_length=200),
        ),
        migrations.AlterField(
            model_name='hub',
            name='vault',
            field=models.CharField(blank=True, choices=[('Raw', 'Bus'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200),
        ),
        migrations.AlterField(
            model_name='hubsatelite',
            name='name',
            field=models.CharField(help_text='This will be the name that the Hub, Satelite, Link etc will be known as', max_length=200),
        ),
        migrations.AlterField(
            model_name='hubsatelite',
            name='schema',
            field=models.CharField(blank=True, help_text='Can be supplied directly, otherwise, derived from the Vault field', max_length=200),
        ),
        migrations.AlterField(
            model_name='hubsatelite',
            name='table_alias',
            field=models.CharField(blank=True, help_text='table Alias will be used when this table is used in joins, and select statements', max_length=200),
        ),
        migrations.AlterField(
            model_name='hubsatelite',
            name='table_name',
            field=models.CharField(blank=True, help_text='Can be entered explicitly, but if blank will be derived from name, and table_naming rules', max_length=200),
        ),
        migrations.AlterField(
            model_name='hubsatelite',
            name='vault',
            field=models.CharField(blank=True, choices=[('Raw', 'Bus'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(help_text='This will be the name that the Hub, Satelite, Link etc will be known as', max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='schema',
            field=models.CharField(blank=True, help_text='Can be supplied directly, otherwise, derived from the Vault field', max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='table_alias',
            field=models.CharField(blank=True, help_text='table Alias will be used when this table is used in joins, and select statements', max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='table_name',
            field=models.CharField(blank=True, help_text='Can be entered explicitly, but if blank will be derived from name, and table_naming rules', max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='vault',
            field=models.CharField(blank=True, choices=[('Raw', 'Bus'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200),
        ),
        migrations.AlterField(
            model_name='linksatelite',
            name='name',
            field=models.CharField(help_text='This will be the name that the Hub, Satelite, Link etc will be known as', max_length=200),
        ),
        migrations.AlterField(
            model_name='linksatelite',
            name='schema',
            field=models.CharField(blank=True, help_text='Can be supplied directly, otherwise, derived from the Vault field', max_length=200),
        ),
        migrations.AlterField(
            model_name='linksatelite',
            name='table_alias',
            field=models.CharField(blank=True, help_text='table Alias will be used when this table is used in joins, and select statements', max_length=200),
        ),
        migrations.AlterField(
            model_name='linksatelite',
            name='table_name',
            field=models.CharField(blank=True, help_text='Can be entered explicitly, but if blank will be derived from name, and table_naming rules', max_length=200),
        ),
        migrations.AlterField(
            model_name='linksatelite',
            name='vault',
            field=models.CharField(blank=True, choices=[('Raw', 'Bus'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200),
        ),
        migrations.AlterField(
            model_name='stagetable',
            name='name',
            field=models.CharField(help_text='This will be the name that the Hub, Satelite, Link etc will be known as', max_length=200),
        ),
        migrations.AlterField(
            model_name='stagetable',
            name='schema',
            field=models.CharField(blank=True, help_text='Can be supplied directly, otherwise, derived from the Vault field', max_length=200),
        ),
        migrations.AlterField(
            model_name='stagetable',
            name='table_alias',
            field=models.CharField(blank=True, help_text='table Alias will be used when this table is used in joins, and select statements', max_length=200),
        ),
        migrations.AlterField(
            model_name='stagetable',
            name='table_name',
            field=models.CharField(blank=True, help_text='Can be entered explicitly, but if blank will be derived from name, and table_naming rules', max_length=200),
        ),
        migrations.AlterField(
            model_name='stagetable',
            name='vault',
            field=models.CharField(blank=True, choices=[('Raw', 'Bus'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200),
        ),
    ]
