# Generated by Django 2.2 on 2019-05-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0013_auto_20190509_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubkeyfield',
            name='field_desciption',
        ),
        migrations.RemoveField(
            model_name='hubsatelitefield',
            name='field_desciption',
        ),
        migrations.RemoveField(
            model_name='linkfield',
            name='field_desciption',
        ),
        migrations.RemoveField(
            model_name='linksatelitefield',
            name='field_desciption',
        ),
        migrations.RemoveField(
            model_name='stagetablefield',
            name='field_desciption',
        ),
        migrations.AddField(
            model_name='hubkeyfield',
            name='field_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hubsatelitefield',
            name='field_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='linkfield',
            name='field_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='linksatelitefield',
            name='field_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stagetablefield',
            name='field_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hub',
            name='vault',
            field=models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200),
        ),
        migrations.AlterField(
            model_name='hubsatelite',
            name='vault',
            field=models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='vault',
            field=models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200),
        ),
        migrations.AlterField(
            model_name='linksatelite',
            name='vault',
            field=models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200),
        ),
        migrations.AlterField(
            model_name='stagetable',
            name='vault',
            field=models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Bus', 'Business')], default='raw', help_text='Determines the vault, and hence schema this entity resides in', max_length=200),
        ),
    ]
