# Generated by Django 2.2 on 2019-05-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0014_auto_20190510_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkhubreference',
            options={'ordering': ['id']},
        ),
    ]
