# Generated by Django 2.2 on 2019-05-10 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0015_auto_20190510_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetablefield',
            name='stage_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.StageTable'),
        ),
    ]
