# Generated by Django 2.2 on 2019-05-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0016_auto_20190510_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkloaderfield',
            old_name='hub_loader',
            new_name='link_loader',
        ),
        migrations.RenameField(
            model_name='linksateliteloaderfield',
            old_name='hub_satelite_loader',
            new_name='link_satelite_loader',
        ),
        migrations.AddField(
            model_name='hubloaderfield',
            name='hub_field_name',
            field=models.CharField(blank=True, help_text='If left blank, the loader will\n                       look for a hub field whose name is the same as this field.  \n                       If this field is populated, then the loader will load \n                       data into the field specified here ', max_length=200),
        ),
        migrations.AddField(
            model_name='hubsateliteloader',
            name='hub_loader',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dventities.HubLoader'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hubsateliteloaderfield',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hubsateliteloaderfield',
            name='create_field_like_this_in_satelite',
            field=models.BooleanField(blank=True, default=False, help_text='If a field with this name does not exist in the satelite, then\n                       a field will be created when this record is saved ', null=True),
        ),
        migrations.AddField(
            model_name='hubsateliteloaderfield',
            name='satelite_field_name',
            field=models.CharField(blank=True, help_text='The satelite field that will get populated by load routines ', max_length=200),
        ),
        migrations.AddField(
            model_name='linkloader',
            name='hub_loaders',
            field=models.ManyToManyField(to='dventities.HubLoader'),
        ),
        migrations.AddField(
            model_name='linksateliteloader',
            name='link_loader',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dventities.LinkLoader'),
            preserve_default=False,
        ),
    ]
