# Generated by Django 2.2 on 2019-05-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0017_auto_20190510_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubkeyfield',
            name='field_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubkeyfield',
            name='field_precision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubkeyfield',
            name='field_scale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubsatelitefield',
            name='field_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubsatelitefield',
            name='field_precision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubsatelitefield',
            name='field_scale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkfield',
            name='field_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkfield',
            name='field_precision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkfield',
            name='field_scale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linksatelitefield',
            name='field_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linksatelitefield',
            name='field_precision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linksatelitefield',
            name='field_scale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagetablefield',
            name='field_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagetablefield',
            name='field_precision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagetablefield',
            name='field_scale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
