# Generated by Django 2.2 on 2019-05-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0018_auto_20190510_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubkeyfield',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dventities.Hub'),
        ),
    ]
