# Generated by Django 2.2 on 2019-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dventities', '0019_auto_20190510_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetablefield',
            name='stage_table_primary_key',
            field=models.BooleanField(blank=True, default=False, help_text='This field represents the primary key of the stage table.  A similar primary key will\n                       be created on the augmented table, and then a view will combined fields in the stage table \n                       with fields in the augmented table', null=True),
        ),
    ]
