# Generated by Django 2.2 on 2019-05-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodegenParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value_string', models.CharField(blank=True, max_length=200)),
                ('value_int', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
